# Generated by Django 5.1.3 on 2024-12-04 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmountCaffeine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='میزان کافئین')),
            ],
            options={
                'verbose_name': 'میزان کافئین',
                'verbose_name_plural': 'میزان کافئین',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان دسته بندی ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس دسته بندی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='product.category', verbose_name='دسته بندی های دیگر')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام محصول')),
                ('origin', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام محصول')),
                ('ingredient', models.CharField(blank=True, max_length=200, null=True, verbose_name='مواد تشکیل دهنده')),
                ('image1', models.ImageField(upload_to='', verbose_name='عکس محصول')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='قیمت محصول')),
                ('discount', models.SmallIntegerField(verbose_name='تخفیف ')),
                ('introduction', models.TextField(verbose_name='توضیحات محصول')),
                ('create', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True, verbose_name='موجود')),
                ('amazingoffers', models.BooleanField(default=False, verbose_name='پیشنهاد شگفت انگیز')),
                ('caffeine', models.ManyToManyField(related_name='caffeine', to='product.amountcaffeine', verbose_name='میزان کافئین ')),
                ('category', models.ManyToManyField(to='product.category', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
